### ISSUE TITLE
Text cleaning function

### ISSUE THREAD

**Issue by Emekaborisama** [Emekaborisama/Tensor_textgen#3]
write a text cleaning function for the training data

- Remove emoji
- Remove hashtag or noise

**Comment by DavidHODs** [comment]
`import re
def cleanText(text):
    emoji = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002500-\U00002BEF"  # chinese char
        u"\U00002702-\U000027B0"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642" 
        u"\u2600-\u2B55"
        u"\u200d"
        u"\u23cf"
        u"\u23e9"
        u"\u231a"
        u"\ufe0f"  # dingbats
        u"\u3030"
                      "]+", re.UNICODE)
    
    text = re.sub(emoji, '', text)
    text = re.sub(r'#\w+', ' ', text)
    
    return text

with open(text, encoding='utf-8') as f:
    Corpus = f.readlines()
Corpus = [cleanText(x) for x in Corpus]
Corpus = ' '.join(Corpus).lower().split('\n')

Corpus`

**Comment by DavidHODs** [comment]
`import re
def cleanText(text):
    emoji = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002500-\U00002BEF"  # chinese char
        u"\U00002702-\U000027B0"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642" 
        u"\u2600-\u2B55"
        u"\u200d"
        u"\u23cf"
        u"\u23e9"
        u"\u231a"
        u"\ufe0f"  # dingbats
        u"\u3030"
                      "]+", re.UNICODE)
    
    text = re.sub(emoji, '', text)
    text = re.sub(r'#\w+', ' ', text)
    
    return text

with open(text, encoding='utf-8') as f:
    Corpus = f.readlines()
Corpus = [cleanText(x) for x in Corpus]
Corpus = ' '.join(Corpus).lower().split('\n')

Corpus`

**Comment by DavidHODs** [comment]
or is there a better way for me to contribute to the issues apart from via the comment box

**Comment by DavidHODs** [comment]
```
import re

def cleanText(text):
    
    '''Removes emojis and hashtags'''
    
    emoji = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002500-\U00002BEF"  # chinese char
        u"\U00002702-\U000027B0"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642" 
        u"\u2600-\u2B55"
        u"\u200d"
        u"\u23cf"
        u"\u23e9"
        u"\u231a"
        u"\ufe0f"  # dingbats
        u"\u3030"
                      "]+", re.UNICODE)
    
    text = re.sub(emoji, '', text)
    text = re.sub(r'#\w+', ' ', text)
    
    return text

with open(text, encoding='utf-8') as f:
    Corpus = f.readlines()
Corpus = [cleanText(x) for x in Corpus]
Corpus = ' '.join(Corpus).lower().split('\n')

Corpus
```

**Comment by DavidHODs** [comment]
```
import re

def cleanText(text):
    
    '''Removes emojis and hashes'''
    
    emoji = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002500-\U00002BEF"  # chinese char
        u"\U00002702-\U000027B0"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642" 
        u"\u2600-\u2B55"
        u"\u200d"
        u"\u23cf"
        u"\u23e9"
        u"\u231a"
        u"\ufe0f"  # dingbats
        u"\u3030"
                      "]+", re.UNICODE)
    
    text = re.sub(emoji, '', text)
    text = re.sub(r'#\w+', ' ', text)
    
    return text

with open(text, encoding='utf-8') as f:
    Corpus = f.readlines()
Corpus = [cleanText(x) for x in Corpus]
Corpus = ' '.join(Corpus).lower().split('\n')

Corpus
```

**Comment by Emekaborisama** [comment]
Thanks
